version: "2.1"

services:
  users-db:
    container_name: usersdb
    build: ./services/postDB/
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0
  seq-webserver:
    container_name: webserver
    build: ./services/seq/
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=usersdb
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
volumes:
  pgdata:
