version: '2.1'

services:

  users-db:
    container_name: users-db-
    build: ./services/postDB/
    volumes:
      - pgdate:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0
  express:
    container_name: express
    build: ./services/express/
    ports:
      - '4000:4000'
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db


